# octocov configuration
# See: https://github.com/k1LoW/octocov

# Coverage reporting from vitest LCOV output
# Badges are generated as shields.io endpoint JSON files by the workflow
# Philosophy: Visibility over enforcement. Alert on regressions, not arbitrary thresholds.
coverage:
  paths:
    - coverage/lcov.info
  # No hard threshold - flag significant drops instead
  acceptable: diff >= -5%

# Code to test ratio
# Measures lines of source code vs test code
# Prevents test bloat while ensuring adequate coverage
codeToTestRatio:
  code:
    - "src/lib/**/*.ts"
    - "src/lib/**/*.svelte"
    - "!src/lib/**/*.test.ts"
    - "!src/lib/**/*.spec.ts"
  test:
    - "src/**/*.test.ts"
    - "src/**/*.spec.ts"
    - "tests/**/*.ts"
  # Alert if ratio drops significantly
  acceptable: diff >= -0.1

# Test execution time (GitHub Actions only)
testExecutionTime:
  # Keep tests fast - alert if they slow down significantly
  # Note: octocov doesn't support compound conditions; CI timeout acts as absolute cap
  acceptable: diff <= 30sec

# PR comment configuration
comment:
  hideFooterLink: false
  deletePrevious: true
  if: is_pull_request
  message: |
    *One coverage percentage! Two code-to-test ratio! Three execution time! Ah ah ah!*

# Summary for GitHub Actions Job Summary
summary:
  if: true

# Store reports for diff comparison
report:
  datastores:
    - artifact://${GITHUB_REPOSITORY}

# Compare against previous reports
diff:
  datastores:
    - artifact://${GITHUB_REPOSITORY}
  if: is_pull_request
